image: maven:latest

stages:
  - build
  - test
  - run
  - deploy

cache:
  paths:
    - target/

build_app:
  stage: build
  script:
    - mvn package

test_app:
  stage: test
  script:
    - mvn test

deploy_app:
    stage: deploy
    script:
    - echo "Deploy review app"
    artifacts:
        name: "my-app"
        paths:
        - target/*.war